require: rubocop-rspec

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/Documentation:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Layout/LineLength:
  Max: 120

Style/ModuleFunction:
  Enabled: false

Layout/HashAlignment:
  EnforcedHashRocketStyle: table

